### ISSUE TITLE
Flag to launch JupyterLab on Casper

### ISSUE THREAD

**Issue by bradyrx** [mnlevy1981/pangeo-tools#2]
Hi Mike. I've been using the launch JupyterLab command here and really appreciate the work you put in on it. Given the PBS issues this morning, I had to manually launch through a Casper node (what a pain! :wink:). I was thinking it might be useful to have a `casper` flag on this launch script to route through `execdav` instead. 

I was thinking of opening a PR for this, but the shell script is pretty involved and I was curious if you had thoughts of where to execute a flag like this.

I imagine you'd need to just submit a slurm script instead at this point.

```shell
s=$(qsub << EOF
  #!/bin/bash
  #PBS -N pangeo
  #PBS -q ${QUEUE}
  #PBS -A ${ACCOUNT}
  #PBS -l select=${NODES}:ncpus=${CORES}:mpiprocs=${CORES}
  #PBS -l walltime=$WALLTIME
  #PBS -j oe
  module purge
  export LD_LIBRARY_PATH=
  ${SET_PY_ENV}
  cd ${ROOT_PATH}
  # FIXME: how do I get the correct hostname here?
  #        (this returns empty string)
  echo "hostname = $(echo '$(hostname)')" > .jupyter_lab.log
  jupyter lab --no-browser --ip=`echo "$(echo '$(hostname)')"` 2>&1 | tee -a .jupyter_lab.log
EOF
  )
SJOB=${s%.*}
``` 

Although there's a few `qstat` commands later that would have to be replaced with slurm commands, etc.

**Comment by mnlevy1981** [comment]
Hmm, that's an interesting idea. FYI, I've updated this script and a better version can be found at [NCAR/pangeo](https://github.com/NCAR/pangeo)... but also, CISL is running a [jupyterhub](https://jupyterhub.ucar.edu/) server so I pretty much stopped maintaining the newer version of this script as well. Have you used the hub at all? I'm not sure if it could get you onto casper when PBS is down, so maybe it's worth updating this script as well... let me play around with it, and I'll probably ask you to review a PR over at the other repository.

**Comment by mnlevy1981** [comment]
You might also want to look at [NCAR/NCAR-pangeo-tutorial](https://github.com/NCAR/NCAR-pangeo-tutorial/), specifically [scripts/jlab-dav](https://github.com/NCAR/NCAR-pangeo-tutorial/blob/master/scripts/jlab-dav) -- it requires multiple terminal windows (one to run `jlab-dav` and one to tunnel in) but don't require as much setup on the cheyenne side as the NCAR/pangeo tool I mentioned above.

**Comment by mnlevy1981** [comment]
@bradyrx -- I added a `launch_pangeo_on_casper` script to a [NCAR/pangeo branch](https://github.com/NCAR/pangeo/tree/casper-support) if you want to try it out. I have done very little testing, basically verified that I can get a notebook running on dav and then pushed my changes.

**Comment by bradyrx** [comment]
@mnlevy1981 -- thanks for all this. I just checked back here manually. For some reason I never got emails of your responses on this thread.  

1. I'll give the `launch_pangeo_on_casper` script a try soon and let you know.

2. I have not tryed out the jupyterhub. I still don't have a clear idea of what it is relative to running my own jupyterhub/notebook. Do you have a succinct explanation? The NCAR-pangeo-tutorial looks helpful. I'll give that a go next time.

**Comment by mnlevy1981** [comment]
I think of jupyterhub as a web interface with the same basic end result as the `launch_pangeo_on_*` scripts -- under the covers it is very different, but you basically use a web page to launch a job on cheyenne that ends up with jupyter lab (or notebook) running in your local browser. The hub is integrated with conda, so you can run different notebooks in different conda environments.

**Comment by bradyrx** [comment]
@mnlevy1981 , thanks! This seems like a much better solution. I didn't realize with the hub you could just log in and get a compute node directly from the browser.
